### ISSUE TITLE
Wrong precision for wavelength 

### ISSUE THREAD

**Issue by antolinos** [ispyb/EXI#280]
on ID30B, the reported wavelength is said to be 1.0A but it is actually 0.976. I think that we should have 3 digits after the point (not 12 as were before). By the way in the summary & beamline parameters, the wavelength is displayed correctly.
could you please check this?

**Comment by antolinos** [comment]
I think he means in the data collection tab
![image](https://user-images.githubusercontent.com/2901169/27853820-9ba4abc4-6164-11e7-99fd-e2c003bec62d.png)

**Comment by antolinos** [comment]
Fixed in version https://github.com/ispyb/EXI/tree/5.0.6
![image](https://user-images.githubusercontent.com/2901169/27854242-59a0eb3c-6166-11e7-8f4f-3ef47aac120a.png)

**Comment by StephMonaco** [comment]
Sorry Alex, I reacted too late. Yes this is the right place but please put 4 decimals and not 3 so that we keep the same convention on all pages ( 4 for the wavelength and 3 for the En).
I have noticed inconsistency with these decimals in the View all collections page. I'll create a new Github entry.
It was already created as #262
